const carData = [
  {
    "car_name": "CRYSTAN Aurora",
    "model": "2022",
    "id":"#aurora",
    "price": 500000,
    "engine": "5.0L V12 Turbo",
    "power": "6500 hp",
    "torque": "450 lb-ft",
    "image": "/Aurora/Aurora (7).jpg",
    "images": ["/Aurora/Aurora (7).jpg",
      "/Aurora/Aurora (2).jpg",
      "/Aurora/Aurora (3).jpg",
      "/Aurora/Aurora (4).jpg",
      "/Aurora/Aurora (5).jpg",
      "/Aurora/Aurora (6).jpg",
      "/Aurora/Aurora (1).jpg",
    ]
  },
  {
    "car_name": "CRYSTAN Zenith",
    "model": "2023",
    "id":"#zenith",
    "price": 60000,
    "engine": "2.5L Inline-6",
    "power": "250 hp",
    "torque": "300 lb-ft",
    "image": "/Zenith/Zenith (6).jpg",
    "images": ["/Zenith/Zenith (6).jpg",
      "/Zenith/Zenith (2).jpg",
      "/Zenith/Zenith (3).jpg",
      "/Zenith/Zenith (4).jpg",
      "/Zenith/Zenith (5).jpg",
      "/Zenith/Zenith (6).jpg"
    ]
  },
  {
    "car_name": "CRYSTAN Nebula",
    "model": "2019",
    "id":"#nebula",
    "price": 70000,
    "engine": "2.0L Turbocharged",
    "power": "280 hp",
    "torque": "320 lb-ft",
    "image": "/Nebula/Nebula1.jpg",
    "images": ["/Nebula/Nebula1.jpg",
      "/Nebula/Nebula2.jpg",
      "/Nebula/Nebula3.jpg",
      "/Nebula/Nebula4.jpg",
      "/Nebula/Nebula5.jpg",
      "/Nebula/Nebula6.jpg",
      "/Nebula/Nebula7.jpg",
    ]
  },
  {
    "car_name": "CRYSTAN Eclipse",
    "model": "2020",
    "id":"#eclipse",
    "price": 80000,
    "engine": "3.5L V6",
    "power": "370 hp",
    "torque": "450 lb-ft",
    "image": "/Eclipse/Eclipse1.jpg",
    "images": ["/Eclipse/Eclipse1.jpg",
      "/Eclipse/Eclipse2.jpg",
      "/Eclipse/Eclipse3.jpg",
      "/Eclipse/Eclipse4.jpg",
      "/Eclipse/Eclipse5.jpg",
      "/Eclipse/Eclipse6.jpg",
    ]
  },
  {
    "car_name": "CRYSTAN Vortex",
    "model": "2017",
    "id":"#vortex",
    "price": 90000,
    "engine": "4.0L V8",
    "power": "500 hp",
    "torque": "480 lb-ft",
    "image": "/Vortex/Vortex1.jpg",
    "images": ["/Vortex/Vortex1.jpg",
      "/Vortex/Vortex2.jpg",
      "/Vortex/Vortex3.jpg",
      "/Vortex/Vortex4.jpg",
      "/Vortex/Vortex5.jpg",
      "/Vortex/Vortex6.jpg",
    ]
  },
  {
    "car_name": "CRYSTAN Nova",
    "model": "2024",
    "id":"#nova",
    "price": 100000,
    "engine": "3.0L V6 Turbo",
    "power": "390 hp",
    "torque": "400 lb-ft",
    "image": "/Nova/Nova (6).jpg",
    "images": ["/Nova/Nova (6).jpg",
      "/Nova/Nova (2).jpg",
      "/Nova/Nova (3).jpg",
      "/Nova/Nova (4).jpg",
      "/Nova/Nova (5).jpg",
      "/Nova/Nova (1).jpg",
    ]
  }


];

export default carData;
